"""Numerical parent-refit gate for equation evolution.

The gate deliberately uses the *already accepted child DataGenSpec*: its fixed
parameters, initial conditions, time span, and sampling box are authoritative.
It never asks an LLM to judge difficulty and it never changes a sampling range.

For an explicit law it fits the parent coefficients to child values at fresh
points in the child's existing box.  For a typed ODE system it evaluates the
parent target-state RHS on a trajectory generated by the child, then fits the
parent coefficients to the child's derivative label.  The latter is explicitly
reported as an RHS-on-child-trajectory test, rather than a full trajectory-fit.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from scipy.optimize import least_squares

from data_generator.generate_from_spec import (
    _declared_symbols,
    _lambdify,
    _sample_axes,
    gen_integrate_system,
)


def _roles(record: dict, role: str) -> list[str]:
    return [symbol for symbol, symbol_role in zip(
        record.get("symbols", []) or [], record.get("symbol_properties", []) or [],
    ) if symbol_role == role]


def _parameter_values(
    parent_record: dict,
    child_spec: dict,
    parent_spec: dict | None,
) -> tuple[list[str], np.ndarray] | tuple[None, str]:
    """Get parent P values without inventing values or changing the spec."""
    names = _roles(parent_record, "P")
    child_values = {
        item["symbol"]: float(item["value"])
        for item in child_spec.get("parameters", []) or []
    }
    parent_values = {
        item["symbol"]: float(item["value"])
        for item in (parent_spec or {}).get("parameters", []) or []
    }
    values: list[float] = []
    missing: list[str] = []
    for name in names:
        if name in child_values:
            values.append(child_values[name])
        elif name in parent_values:
            values.append(parent_values[name])
        else:
            missing.append(name)
    if missing:
        return None, "missing fixed value(s) for parent parameter(s): " + ", ".join(missing)
    return names, np.asarray(values, dtype=float)


def _r2(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    if not (np.all(np.isfinite(y_true)) and np.all(np.isfinite(y_pred))):
        return float("-inf")
    denom = float(np.sum((y_true - np.mean(y_true)) ** 2))
    if denom <= np.finfo(float).eps * max(1.0, float(np.sum(y_true ** 2))):
        # Standard R2 is undefined for an essentially constant target.  Treat it
        # as unassessable instead of producing a misleading huge negative score.
        return float("nan")
    return float(1.0 - np.sum((y_true - y_pred) ** 2) / denom)


def _residual_hotspots(
    axes: list[str],
    values: list[np.ndarray],
    truth: np.ndarray,
    prediction: np.ndarray,
) -> dict:
    """Compact, range-planner-friendly location of the largest parent mismatch."""
    error = np.abs(np.asarray(truth, dtype=float) - np.asarray(prediction, dtype=float))
    if not len(error) or not np.all(np.isfinite(error)):
        return {}
    cutoff = float(np.quantile(error, 0.90))
    mask = error >= cutoff
    return {
        "top_10pct_abs_residual_threshold": cutoff,
        "overall_max_abs_residual": float(np.max(error)),
        "coordinate_ranges": {
            name: [float(np.min(axis[mask])), float(np.max(axis[mask]))]
            for name, axis in zip(axes, values)
        },
    }


def _fit_predict(
    f: Any,
    x_fit: list[np.ndarray],
    y_fit: np.ndarray,
    x_test: list[np.ndarray],
    initial: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, str | None]:
    """Least-squares fit with a finite penalty for invalid symbolic candidates."""
    scale = max(1.0, float(np.nanstd(y_fit)))

    def values(xs: list[np.ndarray], theta: np.ndarray) -> np.ndarray:
        out = np.asarray(f(*xs, *theta), dtype=float)
        return np.broadcast_to(out, xs[0].shape).astype(float)

    def residual(theta: np.ndarray) -> np.ndarray:
        try:
            pred = values(x_fit, theta)
            res = pred - y_fit
            return np.where(np.isfinite(res), res, 1e9 * scale)
        except Exception:
            return np.full(y_fit.shape, 1e9 * scale)

    try:
        if len(initial):
            result = least_squares(residual, initial, max_nfev=3000)
            theta = np.asarray(result.x, dtype=float)
        else:
            theta = initial
        return theta, values(x_test, theta), None
    except Exception as exc:
        return initial, np.full(y_fit.shape, np.nan), f"least_squares failed: {type(exc).__name__}: {exc}"


def _explicit_gate(
    parent_record: dict,
    child_spec: dict,
    parent_spec: dict | None,
    *, fit_seed: int,
    test_seed: int,
    n_fit: int,
    n_test: int,
) -> dict:
    param_result = _parameter_values(parent_record, child_spec, parent_spec)
    if param_result[0] is None:
        return {"status": "unassessable", "mode": "static_explicit", "reason": param_result[1]}
    parent_params, initial = param_result
    ivs = child_spec.get("independent_variables", []) or []
    axes = [item["symbol"] for item in ivs]
    parent_inputs = _roles(parent_record, "V")
    missing_inputs = [name for name in parent_inputs if name not in axes]
    if missing_inputs:
        return {"status": "unassessable", "mode": "static_explicit",
                "reason": "parent input(s) are not sampled by child spec: " + ", ".join(missing_inputs)}
    if not axes:
        return {"status": "unassessable", "mode": "static_explicit", "reason": "child spec has no inputs"}
    try:
        child_p = {p["symbol"]: float(p["value"])
                   for p in child_spec.get("parameters", []) or []}
        child_names = list(child_p)
        child_f, _ = _lambdify(child_spec["rhs_for_integrator"], axes + child_names,
                               force_symbols=_declared_symbols(child_spec))
        parent_f, _ = _lambdify(parent_record["expression"], axes + parent_params,
                                force_symbols=set(axes) | set(parent_params))
        x_fit = _sample_axes(ivs, n_fit, fit_seed)
        x_test = _sample_axes(ivs, n_test, test_seed)
        y_fit = np.asarray(child_f(*x_fit, *[child_p[name] for name in child_names]), dtype=float)
        y_test = np.asarray(child_f(*x_test, *[child_p[name] for name in child_names]), dtype=float)
        y_fit = np.broadcast_to(y_fit, x_fit[0].shape).astype(float)
        y_test = np.broadcast_to(y_test, x_test[0].shape).astype(float)
    except Exception as exc:
        return {"status": "unassessable", "mode": "static_explicit",
                "reason": f"could not evaluate child/parent: {type(exc).__name__}: {exc}"}
    fitted, pred, err = _fit_predict(parent_f, x_fit, y_fit, x_test, initial)
    if err:
        return {"status": "unassessable", "mode": "static_explicit", "reason": err}
    return {
        "status": "assessed", "mode": "static_explicit", "parent_to_child_r2": _r2(y_test, pred),
        "fit_rmse": float(np.sqrt(np.mean((y_fit - np.asarray(parent_f(*x_fit, *fitted))) ** 2))),
        "test_rmse": float(np.sqrt(np.mean((y_test - pred) ** 2))),
        "fitted_parent_parameters": dict(zip(parent_params, map(float, fitted))),
        "residual_hotspots": _residual_hotspots(axes, x_test, y_test, pred),
        "n_fit": int(n_fit), "n_test": int(n_test),
    }


def _ode_gate(
    parent_record: dict,
    child_spec: dict,
    parent_spec: dict | None,
    *, seed: int,
) -> dict:
    param_result = _parameter_values(parent_record, child_spec, parent_spec)
    if param_result[0] is None:
        return {"status": "unassessable", "mode": "ode_rhs_on_child_trajectory", "reason": param_result[1]}
    parent_params, initial = param_result
    if child_spec.get("integrator") != "integrate_system":
        return {"status": "unassessable", "mode": "ode_rhs_on_child_trajectory",
                "reason": "only typed integrate_system ODE specs are currently gateable"}
    parent_ode = parent_record.get("ode_system") or {}
    states = [item.get("symbol") for item in parent_ode.get("states", []) if isinstance(item, dict)]
    target_state = parent_ode.get("target_state")
    if target_state not in states:
        return {"status": "unassessable", "mode": "ode_rhs_on_child_trajectory",
                "reason": "parent ODE target state is unavailable"}
    target_rhs = next(item["rhs"] for item in parent_ode["states"] if item["symbol"] == target_state)
    try:
        columns, data = gen_integrate_system(child_spec, seed)
        lookup = {name: data[:, index] for index, name in enumerate(columns)}
        tname = (child_spec.get("independent_variables") or [{}])[0].get("symbol")
        required = [tname, *states]
        missing = [name for name in required if name not in lookup]
        target_label = child_spec.get("benchmark_output")
        if missing or not target_label or target_label not in lookup:
            return {"status": "unassessable", "mode": "ode_rhs_on_child_trajectory",
                    "reason": "child trajectory lacks parent covariates or derivative label"}
        parent_f, _ = _lambdify(target_rhs, required + parent_params,
                                force_symbols=set(required) | set(parent_params))
        xs = [lookup[name] for name in required]
        truth = lookup[target_label]
        fit_mask = np.arange(len(truth)) % 2 == 0
        test_mask = ~fit_mask
        if test_mask.sum() < 2:
            return {"status": "unassessable", "mode": "ode_rhs_on_child_trajectory", "reason": "trajectory is too short"}
        fitted, pred, err = _fit_predict(parent_f, [x[fit_mask] for x in xs], truth[fit_mask],
                                         [x[test_mask] for x in xs], initial)
        if err:
            return {"status": "unassessable", "mode": "ode_rhs_on_child_trajectory", "reason": err}
        fit_pred = np.asarray(parent_f(*[x[fit_mask] for x in xs], *fitted), dtype=float)
        return {
            "status": "assessed", "mode": "ode_rhs_on_child_trajectory",
            "parent_to_child_r2": _r2(truth[test_mask], pred),
            "fit_rmse": float(np.sqrt(np.mean((truth[fit_mask] - fit_pred) ** 2))),
            "test_rmse": float(np.sqrt(np.mean((truth[test_mask] - pred) ** 2))),
            "fitted_parent_parameters": dict(zip(parent_params, map(float, fitted))),
            "residual_hotspots": _residual_hotspots(required, [x[test_mask] for x in xs],
                                                      truth[test_mask], pred),
            "n_fit": int(fit_mask.sum()), "n_test": int(test_mask.sum()),
        }
    except Exception as exc:
        return {"status": "unassessable", "mode": "ode_rhs_on_child_trajectory",
                "reason": f"could not integrate/evaluate: {type(exc).__name__}: {exc}"}


def evaluate_parent_refit(
    parent_record: dict,
    child_record: dict,
    child_spec: dict,
    *,
    parent_spec: dict | None = None,
    reject_r2: float = 0.90,
    fit_seed: int = 1001,
    test_seed: int = 2001,
    n_fit: int = 1024,
    n_test: int = 1024,
) -> dict:
    """Fit parent parameters to child data and return an auditable gate verdict."""
    if child_spec.get("equation_type") == "static_explicit" and child_spec.get("integrator") == "evaluate_explicit":
        report = _explicit_gate(parent_record, child_spec, parent_spec, fit_seed=fit_seed,
                                test_seed=test_seed, n_fit=n_fit, n_test=n_test)
    elif child_record.get("model_family") == "ode":
        report = _ode_gate(parent_record, child_spec, parent_spec, seed=fit_seed)
    else:
        report = {"status": "unassessable", "mode": "unsupported",
                  "reason": "gate currently supports static_explicit and typed ODE systems"}
    report["threshold_r2"] = float(reject_r2)
    if report.get("status") == "assessed":
        score = report["parent_to_child_r2"]
        if not np.isfinite(score):
            report.update({"accepted": False, "decision": "reject_unassessable_variance",
                           "reason": "child target variance is too small for a meaningful R² gate"})
        elif score > reject_r2:
            report.update({"accepted": False, "decision": "reject_parent_substitutes_child",
                           "reason": f"refitted parent test R²={score:.6g} exceeds {reject_r2:.6g}"})
        else:
            report.update({"accepted": True, "decision": "accept_parent_cannot_substitute_child",
                           "reason": f"refitted parent test R²={score:.6g} is at most {reject_r2:.6g}"})
    else:
        report.update({"accepted": False, "decision": "reject_unassessable", "reason": report.get("reason", "unassessable")})
    return report
